Config = {
  ["UsingESX"]        = true,
  ["UsingESX_V1.2.0"] = false,
  ["UsingKashacters"] = false,
  ["CashAccountName"] = "money",
  ["BankAccountName"] = "bank"
}

Controls = {
Focus = 185,
Grab = 24,
}

furni = {}

furni.objects = {
["Couches"] = {
  [1] = { ["object"] = "miss_rub_couch_01", ["price"] = 0, ["name"] = "vieux Canapé floral" },
  [2] = { ["object"] = "prop_fib_3b_bench", ["price"] = 0, ["name"] = "Chaise à trois places" },
  [3] = { ["object"] = "prop_ld_farm_chair01", ["price"] = 0, ["name"] = "vieux Canapé une place" },
  [4] = { ["object"] = "prop_ld_farm_couch01", ["price"] = 0, ["name"] = "vieux Canapé trois places" },
  [5] = { ["object"] = "prop_ld_farm_couch02", ["price"] = 0, ["name"] = "vieux Canapé" },
  [6] = { ["object"] = "v_res_d_armchair", ["price"] = 0, ["name"] = "vieux Canapé jeune" },
  [7] = { ["object"] = "v_res_fh_sofa", ["price"] = 0, ["name"] = "canapé d'angle" },
  [8] = { ["object"] = "v_res_mp_sofa", ["price"] = 0, ["name"] = "canapé d'angle 2" },
  [9] = { ["object"] = "v_res_d_sofa", ["price"] = 0, ["name"] = "canapé 1" },
  [0] = { ["object"] = "v_res_j_sofa", ["price"] = 0, ["name"] = "canapé 2" },
  [11] = { ["object"] = "v_res_mp_stripchair", ["price"] = 0, ["name"] = "canapé 3" },
  [12] = { ["object"] = "v_res_m_h_sofa_sml", ["price"] = 0, ["name"] = "canapé 4" },
  [13] = { ["object"] = "v_res_r_sofa", ["price"] = 0, ["name"] = "canapé 5" },
  [14] = { ["object"] = "v_res_tre_sofa", ["price"] = 0, ["name"] = "canapé 6" },
  [15] = { ["object"] = "v_res_tre_sofa_mess_a", ["price"] = 0, ["name"] = "canapé 7" },
  [16] = { ["object"] = "v_res_tre_sofa_mess_b", ["price"] = 0, ["name"] = "canapé 8" },
  [17] = { ["object"] = "v_res_tre_sofa_mess_c", ["price"] = 0, ["name"] = "canapé 9" },
  [18] = { ["object"] = "v_res_tt_sofa", ["price"] = 0, ["name"] = "canapé 0" },
  [19] = { ["object"] = "prop_rub_couch02", ["price"] = 0, ["name"] = "canapé 11" },
  [0] = { ["object"] = "apa_mp_h_stn_foot_stool_02", ["price"] = 0, ["name"] = "tabouret 1" },
  [21] = { ["object"] = "apa_mp_h_stn_foot_stool_01", ["price"] = 0, ["name"] = "tabouret 2" },
},

["Chaises"] = {
  [1] = { ["object"] = "v_res_d_highchair", ["price"] = 0, ["name"] = "Chaise haute" },
  [2] = { ["object"] = "v_res_fa_chair01", ["price"] = 0, ["name"] = "Chaise" },
  [3] = { ["object"] = "v_res_fa_chair02", ["price"] = 0, ["name"] = "Chaise" },
  [4] = { ["object"] = "v_res_fh_barcchair", ["price"] = 0, ["name"] = "Chaise haute 2" },
  [5] = { ["object"] = "v_res_fh_dineeamesa", ["price"] = 0, ["name"] = "Chaise de table 1" },
  [6] = { ["object"] = "v_res_fh_dineeamesb", ["price"] = 0, ["name"] = "Chaise de table 2" },
  [7] = { ["object"] = "v_res_fh_dineeamesc", ["price"] = 0, ["name"] = "Chaise de table 3" },
  [8] = { ["object"] = "v_res_fh_easychair", ["price"] = 0, ["name"] = "Chaise" },
  [9] = { ["object"] = "v_res_fh_kitnstool", ["price"] = 0, ["name"] = "Tabouret" },
  [0] = { ["object"] = "v_res_fh_singleseat", ["price"] = 0, ["name"] = "Chaise haute" },
  [11] = { ["object"] = "v_res_jarmchair", ["price"] = 0, ["name"] = "Fauteuil" },
  [12] = { ["object"] = "v_res_j_dinechair", ["price"] = 0, ["name"] = "Chaise de table 4" },
  [13] = { ["object"] = "v_res_j_stool", ["price"] = 0, ["name"] = "Tabouret" },
  [14] = { ["object"] = "v_res_mbchair", ["price"] = 0, ["name"] = "MB Chaise" },
  [15] = { ["object"] = "v_res_m_armchair", ["price"] = 0, ["name"] = "Fauteuil 2" },
  [16] = { ["object"] = "v_res_m_dinechair", ["price"] = 0, ["name"] = "Chaise de table 5" },
  [17] = { ["object"] = "v_res_study_chair", ["price"] = 0, ["name"] = "Chaise de bureau 1" },
  [18] = { ["object"] = "v_res_trev_framechair", ["price"] = 0, ["name"] = "Chaise de bureau 2" },
  [19] = { ["object"] = "v_res_tre_chair", ["price"] = 0, ["name"] = "Chaise" },
  [0] = { ["object"] = "v_res_tre_officechair", ["price"] = 0, ["name"] = "Chaise de bureau 3" },
  [21] = { ["object"] = "v_res_tre_stool", ["price"] = 0, ["name"] = "Tabouret" },
  [22] = { ["object"] = "v_res_tre_stool_leather", ["price"] = 0, ["name"] = "Tabouret en cuir" },
  [23] = { ["object"] = "v_res_tre_stool_scuz", ["price"] = 0, ["name"] = "Tabouret 2" },
  [24] = { ["object"] = "v_med_p_deskchair", ["price"] = 0, ["name"] = "Chaise de bureau 4" },
  [25] = { ["object"] = "v_med_p_easychair", ["price"] = 0, ["name"] = "Chaise facile" },
  [26] = { ["object"] = "v_med_whickerchair1", ["price"] = 0, ["name"] = "Chaise" },
  [27] = { ["object"] = "prop_direct_chair_01", ["price"] = 0, ["name"] = "Chaise 1" },
  [28] = { ["object"] = "prop_direct_chair_02", ["price"] = 0, ["name"] = "Chaise 2" },
  [29] = { ["object"] = "prop_yacht_lounger", ["price"] = 0, ["name"] = "Siege de yacht 1" },
  [0] = { ["object"] = "prop_yacht_seat_01", ["price"] = 0, ["name"] = "Siege de yacht 2" },
  [31] = { ["object"] = "prop_yacht_seat_02", ["price"] = 0, ["name"] = "Siege de yacht 3" },
  [32] = { ["object"] = "prop_yacht_seat_03", ["price"] = 0, ["name"] = "Siege de yacht 4" },
  [33] = { ["object"] = "v_ret_chair_white", ["price"] = 0, ["name"] = "Chaise blanche" },
  [34] = { ["object"] = "v_ret_chair", ["price"] = 0, ["name"] = "Chaise" },
  [35] = { ["object"] = "v_ret_ta_stool", ["price"] = 0, ["name"] = "Tabouret" },
  [36] = { ["object"] = "prop_cs_office_chair", ["price"] = 0, ["name"] = "Chaise de bureau 5" },
},

["Lits"] = {
  [1] = { ["object"] = "v_res_d_bed", ["price"] = 0, ["name"] = "Lit 1" },  
  [2] = { ["object"] = "v_res_lestersbed", ["price"] = 0, ["name"] = "Lit 2" }, 
  [3] = { ["object"] = "v_res_mbbed", ["price"] = 0, ["name"] = "Lit 3" }, 
  [4] = { ["object"] = "v_res_mdbed", ["price"] = 0, ["name"] = "Lit 4" }, 
  [5] = { ["object"] = "v_res_msonbed", ["price"] = 0, ["name"] = "Lit 5" },  
  [6] = { ["object"] = "v_res_tre_bed1", ["price"] = 0, ["name"] = "Lit 6" }, 
  [7] = { ["object"] = "v_res_tre_bed2", ["price"] = 0, ["name"] = "Lit 7" }, 
  [8] = { ["object"] = "v_res_tt_bed", ["price"] = 0, ["name"] = "Lit 8" },
  [9] = { ["object"] = "apa_mp_h_bed_double_08", ["price"] = 0, ["name"] = "Lit double" },  
  [0] = { ["object"] = "apa_mp_h_bed_double_09", ["price"] = 0, ["name"] = "Lit double 2" },
  [11] = { ["object"] = "apa_mp_h_bed_wide_05", ["price"] = 0, ["name"] = "Lit double 3" },
  [12] = { ["object"] = "apa_mp_h_bed_with_table_02", ["price"] = 0, ["name"] = "Lit avec table" },
  [13] = { ["object"] = "gr_prop_bunker_bed_01", ["price"] = 0, ["name"] = "bed simple" },
},

["General #1"] = {
  [1] = { ["object"] = "v_corp_facebeanbag", ["price"] = 0, ["name"] = "Sac de haricot 1" },
  [2] = { ["object"] = "v_res_cherubvase", ["price"] = 0, ["name"] = "Vase blanc" },
  [3] = { ["object"] = "v_res_d_paddedwall", ["price"] = 0, ["name"] = "Mur rembourrée" },
  [4] = { ["object"] = "v_res_d_ramskull", ["price"] = 0, ["name"] = "article" },
  [5] = { ["object"] = "v_res_d_whips", ["price"] = 0, ["name"] = "Whips" },
  [6] = { ["object"] = "v_res_fashmag1", ["price"] = 0, ["name"] = "Magasines" },
  [7] = { ["object"] = "v_res_fashmagopen", ["price"] = 0, ["name"] = "Magasines ouverts" },
  [8] = { ["object"] = "v_res_fa_magtidy", ["price"] = 0, ["name"] = "Magasines rangés" },
  [9] = { ["object"] = "v_res_fa_yogamat02", ["price"] = 0, ["name"] = "Materiel de yoga 1" },
  [0] = { ["object"] = "v_res_fa_yogamat1", ["price"] = 0, ["name"] = "Materiel de yoga 2" },
  [11] = { ["object"] = "v_res_fh_aftershavebox", ["price"] = 0, ["name"] = "Après rasage" },
  [12] = { ["object"] = "v_res_fh_flowersa", ["price"] = 0, ["name"] = "Fleurs" },
  [13] = { ["object"] = "v_res_fh_fruitbowl", ["price"] = 0, ["name"] = "bol de fruits" },
  [14] = { ["object"] = "v_res_fh_laundrybasket", ["price"] = 0, ["name"] = "blanchisserie" },
  [15] = { ["object"] = "v_res_fh_pouf", ["price"] = 0, ["name"] = "Pouf" },
  [16] = { ["object"] = "v_res_fh_sculptmod", ["price"] = 0, ["name"] = "Sculpture" },
  [17] = { ["object"] = "v_res_j_magrack", ["price"] = 0, ["name"] = "Grille de rangement" },
  [18] = { ["object"] = "v_res_jewelbox", ["price"] = 0, ["name"] = "Boite à bijoux" },
  [19] = { ["object"] = "v_res_mbbin", ["price"] = 0, ["name"] = "Poubelle" },
  [0] = { ["object"] = "v_res_mbowlornate", ["price"] = 0, ["name"] = "Bol ordonné" },
  [21] = { ["object"] = "v_res_mbronzvase", ["price"] = 0, ["name"] = "Vase de Bronze" },
  [22] = { ["object"] = "v_res_mchalkbrd", ["price"] = 0, ["name"] = "Tableau de craie" },
  [23] = { ["object"] = "v_res_mddresser", ["price"] = 0, ["name"] = "Commode" },
  [24] = { ["object"] = "v_res_mplinth", ["price"] = 0, ["name"] = "Linth" },
  [25] = { ["object"] = "v_res_mp_ashtrayb", ["price"] = 0, ["name"] = "Cebdrier" },
  [26] = { ["object"] = "v_res_m_candle", ["price"] = 0, ["name"] = "Bougie" },
  [27] = { ["object"] = "v_res_m_candlelrg", ["price"] = 0, ["name"] = "Bougie Large" },
  [28] = { ["object"] = "v_res_m_kscales", ["price"] = 0, ["name"] = "Balance" },
  [29] = { ["object"] = "v_res_tt_bedpillow", ["price"] = 0, ["name"] = "Lit avec oreiller" },
  [0] = { ["object"] = "apa_p_h_acc_artwallm_04", ["price"] = 0, ["name"] = "Mur Artistique 1" },
  [31] = { ["object"] = "apa_p_h_acc_artwallm_03", ["price"] = 0, ["name"] = "Mur Artistique 2" },
  [32] = { ["object"] = "apa_p_h_acc_artwallm_01", ["price"] = 0, ["name"] = "Mur Artistique 3" },
  [33] = { ["object"] = "apa_p_h_acc_artwalll_04", ["price"] = 0, ["name"] = "Mur Artistique 4" },
  [34] = { ["object"] = "apa_p_h_acc_artwalll_03", ["price"] = 0, ["name"] = "Mur Artistique 5" },
  [35] = { ["object"] = "apa_mp_h_acc_rugwooll_03", ["price"] = 0, ["name"] = "Couverture 1" },
  [36] = { ["object"] = "apa_mp_h_acc_rugwoolm_04", ["price"] = 0, ["name"] = "Couverture 2" },
  [37] = { ["object"] = "apa_mp_h_acc_rugwools_03", ["price"] = 0, ["name"] = "Couverture 3" },
},

["General #2"] = {
  [1] = { ["object"] = "prop_a4_pile_01", ["price"] = 0, ["name"] = "Pile de feuille A4" },
  [2] = { ["object"] = "prop_amb_40oz_03", ["price"] = 0, ["name"] = "40 onces" },
  [3] = { ["object"] = "prop_amb_beer_bottle", ["price"] = 0, ["name"] = "Bière" },
  [4] = { ["object"] = "prop_aviators_01", ["price"] = 0, ["name"] = "Aviateurs" },
  [5] = { ["object"] = "prop_barry_table_detail", ["price"] = 0, ["name"] = "Detail" },
  [6] = { ["object"] = "prop_beer_box_01", ["price"] = 0, ["name"] = "Bières" },
  [7] = { ["object"] = "prop_binoc_01", ["price"] = 0, ["name"] = "lunettes" },
  [8] = { ["object"] = "prop_blox_spray", ["price"] = 0, ["name"] = "Blox Spray" },
  [9] = { ["object"] = "prop_bongos_01", ["price"] = 0, ["name"] = "Bongos" },
  [0] = { ["object"] = "prop_bong_01", ["price"] = 0, ["name"] = "Bong" },
  [11] = { ["object"] = "prop_boombox_01", ["price"] = 0, ["name"] = "getho blaster" },
  [12] = { ["object"] = "prop_bowl_crisps", ["price"] = 0, ["name"] = "Bol de chips" },
  [13] = { ["object"] = "prop_candy_pqs", ["price"] = 0, ["name"] = "friandises" },
  [14] = { ["object"] = "prop_carrier_bag_01", ["price"] = 0, ["name"] = "sac de carrière" },
  [15] = { ["object"] = "prop_ceramic_jug_01", ["price"] = 0, ["name"] = "Cruche en céramique" },
  [16] = { ["object"] = "prop_cigar_pack_01", ["price"] = 0, ["name"] = "Paquet de cigars 1" },
  [17] = { ["object"] = "prop_cigar_pack_02", ["price"] = 0, ["name"] = "Paquet de cigars 2" },
  [18] = { ["object"] = "prop_cs_beer_box", ["price"] = 0, ["name"] = "Boite à bière 2" },
  [19] = { ["object"] = "prop_cs_binder_01", ["price"] = 0, ["name"] = "Classeur" },
  [0] = { ["object"] = "prop_cs_bs_cup", ["price"] = 0, ["name"] = "Coupe" },
  [21] = { ["object"] = "prop_cs_cashenvelope", ["price"] = 0, ["name"] = "Envelope" },
  [22] = { ["object"] = "prop_cs_champ_flute", ["price"] = 0, ["name"] = "Flute" },
  [23] = { ["object"] = "prop_cs_duffel_01", ["price"] = 0, ["name"] = "Sac molletonné" },
  [24] = { ["object"] = "prop_cs_dvd", ["price"] = 0, ["name"] = "DVD" },
  [25] = { ["object"] = "prop_cs_dvd_case", ["price"] = 0, ["name"] = "Casier à DVD" },
  [26] = { ["object"] = "prop_cs_film_reel_01", ["price"] = 0, ["name"] = "Bobine de film" },
  [27] = { ["object"] = "prop_cs_ilev_blind_01", ["price"] = 0, ["name"] = "Aveugle" },
  [28] = { ["object"] = "p_ld_bs_bag_01", ["price"] = 0, ["name"] = "Sac à dos" },
  [29] = { ["object"] = "prop_cs_ironing_board", ["price"] = 0, ["name"] = "Planche à repasser" },
  [0] = { ["object"] = "prop_cs_katana_01", ["price"] = 0, ["name"] = "Katana" },
  [31] = { ["object"] = "prop_cs_kettle_01", ["price"] = 0, ["name"] = "bouilloire" },
  [32] = { ["object"] = "prop_cs_lester_crate", ["price"] = 0, ["name"] = "Caisse" },
  [33] = { ["object"] = "prop_cs_petrol_can", ["price"] = 0, ["name"] = "Bidon d'essence" },
  [34] = { ["object"] = "prop_cs_sack_01", ["price"] = 0, ["name"] = "Sac" },
  [35] = { ["object"] = "prop_cs_script_bottle_01", ["price"] = 0, ["name"] = "Bouteille" },
  [36] = { ["object"] = "prop_cs_script_bottle", ["price"] = 0, ["name"] = "Bouteille 2" },
  [37] = { ["object"] = "prop_cs_street_binbag_01", ["price"] = 0, ["name"] = "Sac poubelle" },
  [38] = { ["object"] = "prop_cs_whiskey_bottle", ["price"] = 0, ["name"] = "Bouteille de whisky" },
  [39] = { ["object"] = "prop_sh_bong_01", ["price"] = 0, ["name"] = "Bong" },
  [40] = { ["object"] = "prop_peanut_bowl_01", ["price"] = 0, ["name"] = "cacahuètes" },
  [41] = { ["object"] = "prop_tumbler_01", ["price"] = 0, ["name"] = "Verre" },
},

["General #3"] = {
  [1] = { ["object"] = "v_ret_csr_bin", ["price"] = 0, ["name"] = "CSR Bin" },
  [2] = { ["object"] = "v_ret_fh_wickbskt", ["price"] = 0, ["name"] = "Basquette" },
  [3] = { ["object"] = "v_ret_gc_bag01", ["price"] = 0, ["name"] = "Sac à dos 1" },
  [4] = { ["object"] = "v_ret_gc_bag02", ["price"] = 0, ["name"] = "Sac à dos 2" },
  [5] = { ["object"] = "v_ret_gc_bin", ["price"] = 0, ["name"] = "GC Bin" },
  [6] = { ["object"] = "v_ret_gc_cashreg", ["price"] = 0, ["name"] = "Caisse enregistreuse" },
  [7] = { ["object"] = "v_ret_gc_chair01", ["price"] = 0, ["name"] = "Chaise 01" },
  [8] = { ["object"] = "v_ret_gc_chair02", ["price"] = 0, ["name"] = "Chaise 02" },
  [9] = { ["object"] = "v_ret_gc_clock", ["price"] = 0, ["name"] = "Horloge" },
  [0] = { ["object"] = "v_ret_hd_prod1_", ["price"] = 0, ["name"] = "Prod 1" },
  [11] = { ["object"] = "v_ret_hd_prod2_", ["price"] = 0, ["name"] = "Prod 2" },
  [12] = { ["object"] = "v_ret_hd_prod3_", ["price"] = 0, ["name"] = "Prod 3" },
  [13] = { ["object"] = "v_ret_hd_prod4_", ["price"] = 0, ["name"] = "Prod 4" },
  [14] = { ["object"] = "v_ret_hd_prod5_", ["price"] = 0, ["name"] = "Prod 5" },
  [15] = { ["object"] = "v_ret_hd_prod6_", ["price"] = 0, ["name"] = "Prod 6" },
  [16] = { ["object"] = "v_ret_hd_unit1_", ["price"] = 0, ["name"] = "HD Unit 1" },
  [17] = { ["object"] = "v_ret_hd_unit2_", ["price"] = 0, ["name"] = "HD Unit 2" },
  [18] = { ["object"] = "v_ret_ml_fridge02", ["price"] = 0, ["name"] = "Frigo" },
  [19] = { ["object"] = "v_ret_ps_bag_01", ["price"] = 0, ["name"] = "Sac à dos 1" },
  [0] = { ["object"] = "v_ret_ps_bag_02", ["price"] = 0, ["name"] = "Sac à dos 2" },
  [21] = { ["object"] = "v_ret_ta_book1", ["price"] = 0, ["name"] = "Livres 1" },
  [22] = { ["object"] = "v_ret_ta_book2", ["price"] = 0, ["name"] = "Livres 2" },
  [23] = { ["object"] = "v_ret_ta_book3", ["price"] = 0, ["name"] = "Livres 3" },
  [24] = { ["object"] = "v_ret_ta_book4", ["price"] = 0, ["name"] = "Livres 4" },
  [25] = { ["object"] = "v_ret_ta_camera", ["price"] = 0, ["name"] = "Caméra" },
  [26] = { ["object"] = "v_ret_ta_firstaid", ["price"] = 0, ["name"] = "premier secours" },
  [27] = { ["object"] = "v_ret_ta_hero", ["price"] = 0, ["name"] = "Hero" },
  [28] = { ["object"] = "v_ret_ta_mag1", ["price"] = 0, ["name"] = "Mag 1" },
  [29] = { ["object"] = "v_ret_ta_mag2", ["price"] = 0, ["name"] = "Mag 2" },
  [0] = { ["object"] = "v_ret_ta_skull", ["price"] = 0, ["name"] = "Crâne" },
  [31] = { ["object"] = "prop_acc_guitar_01", ["price"] = 0, ["name"] = "Guitare" },
  [32] = { ["object"] = "prop_amb_handbag_01", ["price"] = 0, ["name"] = "Sac à main" },
  [33] = { ["object"] = "prop_attache_case_01", ["price"] = 0, ["name"] = "Case" },
  [34] = { ["object"] = "prop_big_bag_01", ["price"] = 0, ["name"] = "Grand Sac à dos" },
  [35] = { ["object"] = "prop_bonesaw", ["price"] = 0, ["name"] = "Scie à os" },
  [36] = { ["object"] = "prop_cs_fertilizer", ["price"] = 0, ["name"] = "Fertiliseur" },
  [37] = { ["object"] = "prop_cs_shopping_bag", ["price"] = 0, ["name"] = "Sac à dos de shopping" },
  [38] = { ["object"] = "prop_cs_vial_01", ["price"] = 0, ["name"] = "Fiole" },
  [39] = { ["object"] = "prop_defilied_ragdoll_01", ["price"] = 0, ["name"] = "Ragdoll" }, 
},

["General #4"] = {
  [1] = { ["object"] = "prop_dummy_01", ["price"] = 0, ["name"] = "Mannequin" },
  [2] = { ["object"] = "prop_egg_clock_01", ["price"] = 0, ["name"] = "Horloge" },
  [3] = { ["object"] = "prop_el_guitar_01", ["price"] = 0, ["name"] = "Guitare 1" },
  [4] = { ["object"] = "prop_el_guitar_02", ["price"] = 0, ["name"] = "Guitare 2" },
  [5] = { ["object"] = "prop_el_guitar_03", ["price"] = 0, ["name"] = "Guitare 2" },
  [6] = { ["object"] = "prop_feed_sack_01", ["price"] = 0, ["name"] = "Sac d'alimentation" },
  [7] = { ["object"] = "prop_floor_duster_01", ["price"] = 0, ["name"] = "Plumeau d'appartement" },
  [8] = { ["object"] = "prop_fruit_basket", ["price"] = 0, ["name"] = "Corbeille de fruits" },
  [9] = { ["object"] = "prop_f_duster_02", ["price"] = 0, ["name"] = "plumeau" },
  [0] = { ["object"] = "prop_grapes_02", ["price"] = 0, ["name"] = "raisins" },
  [11] = { ["object"] = "prop_hotel_clock_01", ["price"] = 0, ["name"] = "Horloge d'hotel" },
  [12] = { ["object"] = "prop_idol_case_01", ["price"] = 0, ["name"] = "Cas d'idole" },
  [13] = { ["object"] = "prop_jewel_02a", ["price"] = 0, ["name"] = "Bijoux" },
  [14] = { ["object"] = "prop_jewel_02b", ["price"] = 0, ["name"] = "Bijoux" },
  [15] = { ["object"] = "prop_jewel_02c", ["price"] = 0, ["name"] = "Bijoux" },
  [16] = { ["object"] = "prop_jewel_03a", ["price"] = 0, ["name"] = "Bijoux" },
  [17] = { ["object"] = "prop_jewel_03b", ["price"] = 0, ["name"] = "Bijoux" },
  [18] = { ["object"] = "prop_jewel_04a", ["price"] = 0, ["name"] = "Bijoux" },
  [19] = { ["object"] = "prop_jewel_04b", ["price"] = 0, ["name"] = "Bijoux" },
  [0] = { ["object"] = "prop_j_disptray_01", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [21] = { ["object"] = "prop_j_disptray_01b", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [22] = { ["object"] = "prop_j_disptray_02", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [23] = { ["object"] = "prop_j_disptray_03", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [24] = { ["object"] = "prop_j_disptray_04", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [25] = { ["object"] = "prop_j_disptray_04b", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [26] = { ["object"] = "prop_j_disptray_05", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [27] = { ["object"] = "prop_j_disptray_05b", ["price"] = 0, ["name"] = "Plateaux d'affichage" },
  [28] = { ["object"] = "prop_ld_greenscreen_01", ["price"] = 0, ["name"] = "Ecran vert" },
  [29] = { ["object"] = "prop_ld_handbag", ["price"] = 0, ["name"] = "Bagages à main" },
  [0] = { ["object"] = "prop_ld_jerrycan_01", ["price"] = 0, ["name"] = "Jerry Can" },
  [31] = { ["object"] = "prop_ld_keypad_01", ["price"] = 0, ["name"] = "clavier 1" },
  [32] = { ["object"] = "prop_ld_keypad_01b", ["price"] = 0, ["name"] = "clavier 2" },
  [33] = { ["object"] = "prop_ld_suitcase_01", ["price"] = 0, ["name"] = "valise 1" },
  [34] = { ["object"] = "prop_ld_suitcase_02", ["price"] = 0, ["name"] = "valise 2" },
  [35] = { ["object"] = "hei_p_attache_case_shut", ["price"] = 0, ["name"] = "valise 3"},
  [36] = { ["object"] = "prop_mr_rasberryclean", ["price"] = 0, ["name"] = "Framboise propre" },
  [37] = { ["object"] = "prop_paper_bag_01", ["price"] = 0, ["name"] = "Sac à dos en papier" },
  [38] = { ["object"] = "prop_shopping_bags01", ["price"] = 0, ["name"] = "sac de course 1" },
  [39] = { ["object"] = "prop_shopping_bags02", ["price"] = 0, ["name"] = "sac de course 2" },
  [40] = { ["object"] = "prop_yoga_mat_01", ["price"] = 0, ["name"] = "Matériel de Yoga 1" },
  [41] = { ["object"] = "prop_yoga_mat_02", ["price"] = 0, ["name"] = "Matériel de Yoga 2" },
  [42] = { ["object"] = "prop_yoga_mat_03", ["price"] = 0, ["name"] = "Matériel de Yoga 3" },
  [43] = { ["object"] = "p_ld_sax", ["price"] = 0, ["name"] = "Saxophone" },
  [44] = { ["object"] = "p_ld_soc_ball_01", ["price"] = 0, ["name"] = "ballon de foot" },
  [45] = { ["object"] = "p_watch_01", ["price"] = 0, ["name"] = "Montre 1" },
  [46] = { ["object"] = "p_watch_02", ["price"] = 0, ["name"] = "Montre 2" },
  [47] = { ["object"] = "p_watch_03", ["price"] = 0, ["name"] = "Montre 3" },
  [48] = { ["object"] = "p_watch_04", ["price"] = 0, ["name"] = "Montre 4" },
  [49] = { ["object"] = "p_watch_05", ["price"] = 0, ["name"] = "Montre 5" },
  [51] = { ["object"] = "p_watch_06", ["price"] = 0, ["name"] = "Montre 6" },
},

["Small"] = {
  [1] = { ["object"] = "v_res_r_figcat", ["price"] = 0, ["name"] = "figure de Chat" },
  [2] = { ["object"] = "v_res_r_figclown", ["price"] = 0, ["name"] = "figure de Clown" },
  [3] = { ["object"] = "v_res_r_figauth2", ["price"] = 0, ["name"] = "figure d'Autheu" },
  [4] = { ["object"] = "v_res_r_figfemale", ["price"] = 0, ["name"] = "figure de femme" },
  [5] = { ["object"] = "v_res_r_figflamenco", ["price"] = 0, ["name"] = "figure de Flamenco" },
  [6] = { ["object"] = "v_res_r_figgirl", ["price"] = 0, ["name"] = "figure de fille" },
  [7] = { ["object"] = "v_res_r_figgirlclown", ["price"] = 0, ["name"] = "figure de clown fille" },
  [8] = { ["object"] = "v_res_r_figoblisk", ["price"] = 0, ["name"] = "figure Oblisk" },
  [9] = { ["object"] = "v_res_r_figpillar", ["price"] = 0, ["name"] = "figure de pilleur" },
  [0] = { ["object"] = "v_res_r_teapot", ["price"] = 0, ["name"] = "pot à thé" },
  [11] = { ["object"] = "v_res_sculpt_dec", ["price"] = 0, ["name"] = "Sculpture 1" },
  [12] = { ["object"] = "v_res_sculpt_decd", ["price"] = 0, ["name"] = "Sculpture 2" },
  [13] = { ["object"] = "v_res_sculpt_dece", ["price"] = 0, ["name"] = "Sculpture 3" },
  [14] = { ["object"] = "v_res_sculpt_decf", ["price"] = 0, ["name"] = "Sculpture 4" },
  [15] = { ["object"] = "v_res_skateboard", ["price"] = 0, ["name"] = "Skate" },
  [16] = { ["object"] = "v_res_sketchpad", ["price"] = 0, ["name"] = "Sketchpad" },
  [17] = { ["object"] = "v_res_tissues", ["price"] = 0, ["name"] = "Tissus" },
  [18] = { ["object"] = "v_res_tre_basketmess", ["price"] = 0, ["name"] = "Basquettes" },
  [19] = { ["object"] = "v_res_tre_bin", ["price"] = 0, ["name"] = "Poubelle" },
  [0] = { ["object"] = "v_res_tre_cushiona", ["price"] = 0, ["name"] = "Coussin 1" },
  [21] = { ["object"] = "v_res_tre_cushionb", ["price"] = 0, ["name"] = "Coussin 2" },
  [22] = { ["object"] = "v_res_tre_cushionc", ["price"] = 0, ["name"] = "Coussin 3" },
  [23] = { ["object"] = "v_res_tre_cushiond", ["price"] = 0, ["name"] = "Coussin 4" },
  [24] = { ["object"] = "v_res_tre_cushnscuzb", ["price"] = 0, ["name"] = "Coussin 5" },
  [25] = { ["object"] = "v_res_tre_cushnscuzd", ["price"] = 0, ["name"] = "Coussin 6" },
  [26] = { ["object"] = "v_res_tre_fruitbowl", ["price"] = 0, ["name"] = "Bol de fruits" },
  [27] = { ["object"] = "v_med_p_sideboard", ["price"] = 0, ["name"] = "Buffer" },
  [28] = { ["object"] = "prop_idol_01", ["price"] = 0, ["name"] = "Idole 1" },
  [29] = { ["object"] = "p_cs_cuffs_02_s", ["price"] = 0, ["name"] = "Manchette" },
  [0] = { ["object"] = "prop_cs_dildo_01", ["price"] = 0, ["name"] = "Bonnes vibrations" },
  [31] = { ["object"] = "v_res_d_dildo_a", ["price"] = 0, ["name"] = "Bonnes vibrations 2" },
  [32] = { ["object"] = "v_res_d_dildo_b", ["price"] = 0, ["name"] = "Bonnes vibrations 3" },
  [33] = { ["object"] = "v_res_d_dildo_c", ["price"] = 0, ["name"] = "Bonnes vibrations 4" },
  [34] = { ["object"] = "v_res_d_lube", ["price"] = 0, ["name"] = "Lube" },
  [35] = { ["object"] = "v_ret_gc_trays", ["price"] = 0, ["name"] = "plateau de bureau" },
  [36] = { ["object"] = "v_res_filebox01", ["price"] = 0, ["name"] = "boite à dossier" },
},

["Storage"] = {
  [1] = { ["object"] = "v_res_cabinet", ["price"] = 0, ["name"] = "Large Cabinet" },
  [2] = { ["object"] = "v_res_d_dressingtable", ["price"] = 0, ["name"] = "Table de Dressing" },
  [3] = { ["object"] = "v_res_d_sideunit", ["price"] = 0, ["name"] = "Unité latérale" },
  [4] = { ["object"] = "v_res_fh_sidebrddine", ["price"] = 0, ["name"] = "Unité latérale" },
  [5] = { ["object"] = "v_res_fh_sidebrdlngb", ["price"] = 0, ["name"] = "Unité latérale" },
  [6] = { ["object"] = "v_res_mbbedtable", ["price"] = 0, ["name"] = "Lit" },
  [7] = { ["object"] = "v_res_j_tvstand", ["price"] = 0, ["name"] = "Tv" },
  [8] = { ["object"] = "v_res_mbdresser", ["price"] = 0, ["name"] = "Dressing" },
  [9] = { ["object"] = "v_res_mbottoman", ["price"] = 0, ["name"] = "Bottoman Unit" },
  [0] = { ["object"] = "v_res_mconsolemod", ["price"] = 0, ["name"] = "Console" },
  [11] = { ["object"] = "v_res_mcupboard", ["price"] = 0, ["name"] = "Placard" },
  [12] = { ["object"] = "v_res_mdchest", ["price"] = 0, ["name"] = "Poitrine" },
  [13] = { ["object"] = "v_res_msoncabinet", ["price"] = 0, ["name"] = "Mason" },
  [14] = { ["object"] = "v_res_m_armoire", ["price"] = 0, ["name"] = "Armoire" },
  [15] = { ["object"] = "v_res_m_sidetable", ["price"] = 0, ["name"] = "Coté" },
  [16] = { ["object"] = "v_res_son_desk", ["price"] = 0, ["name"] = "Bureau" },
  [17] = { ["object"] = "v_res_tre_bedsidetable", ["price"] = 0, ["name"] = "coté" },
  [18] = { ["object"] = "v_res_tre_bedsidetableb", ["price"] = 0, ["name"] = "coté 2" },
  [19] = { ["object"] = "v_res_tre_smallbookshelf", ["price"] = 0, ["name"] = "Livres" },
  [0] = { ["object"] = "v_res_tre_storagebox", ["price"] = 0, ["name"] = "Boite" },
  [21] = { ["object"] = "v_res_tre_storageunit", ["price"] = 0, ["name"] = "Coffre-fort" },
  [22] = { ["object"] = "v_res_tre_wardrobe", ["price"] = 0, ["name"] = "Armoire" },
  [23] = { ["object"] = "v_res_tre_wdunitscuz", ["price"] = 0, ["name"] = "bois" },
  [24] = { ["object"] = "prop_devin_box_closed", ["price"] = 0, ["name"] = "Sac à dos d'haricots 1" },
  [25] = { ["object"] = "prop_mil_crate_01", ["price"] = 0, ["name"] = "Caisse de lait 1" },
  [26] = { ["object"] = "prop_mil_crate_02", ["price"] = 0, ["name"] = "Caisse de lait 2" },
  [27] = { ["object"] = "prop_ld_int_safe_01", ["price"] = 0, ["name"] = "Sécurité" },
},

["Electronics"] = {
  [1] = { ["object"] = "prop_trailr_fridge", ["price"] = 0, ["name"] = "Vieux frigo" },
  [2] = { ["object"] = "v_res_fh_speaker", ["price"] = 0, ["name"] = "Haut-parleur" },
  [3] = { ["object"] = "v_res_fh_speakerdock", ["price"] = 0, ["name"] = "Station Haut-parleur" },
  [4] = { ["object"] = "v_res_fh_bedsideclock", ["price"] = 0, ["name"] = "Réveil" },
  [5] = { ["object"] = "v_res_fa_phone", ["price"] = 0, ["name"] = "Téléphone" },
  [6] = { ["object"] = "v_res_fh_towerfan", ["price"] = 0, ["name"] = "Tour de fan" },
  [7] = { ["object"] = "v_res_fa_fan", ["price"] = 0, ["name"] = "Fan" },
  [8] = { ["object"] = "v_res_lest_bigscreen", ["price"] = 0, ["name"] = "Grande photo" },
  [9] = { ["object"] = "v_res_lest_monitor", ["price"] = 0, ["name"] = "Télé" },
  [0] = { ["object"] = "v_res_tre_mixer", ["price"] = 0, ["name"] = "Mixer" },
  [11] = { ["object"] = "prop_cs_cctv", ["price"] = 0, ["name"] = "CCTV" },
  [12] = { ["object"] = "prop_ld_lap_top", ["price"] = 0, ["name"] = "ordinateur portable" },
  [13] = { ["object"] = "prop_ld_monitor_01", ["price"] = 0, ["name"] = "Télé" },
  [14] = { ["object"] = "xm_prop_x17_tv_flat_02", ["price"] = 0, ["name"] = "télévision plate" },
  [15] = { ["object"] = "apa_mp_h_str_avunitm_03", ["price"] = 0, ["name"] = "TV 1" },
  [16] = { ["object"] = "apa_mp_h_str_avunits_01", ["price"] = 0, ["name"] = "TV 2" },
  [17] = { ["object"] = "apa_mp_h_str_avunits_04", ["price"] = 0, ["name"] = "TV 3" },
  [18] = { ["object"] = "bkr_prop_clubhouse_jukebox_02a", ["price"] = 0, ["name"] = "Jukebox" },
  [19] = { ["object"] = "bkr_prop_weed_fan_floor_01a", ["price"] = 0, ["name"] = "intérieur fan" },
  [0] = { ["object"] = "prop_cs_keyboard_01", ["price"] = 0, ["name"] = "Clavier d'ordi" },
  [21] = { ["object"] = "ex_mp_h_acc_coffeemachine_01", ["price"] = 0, ["name"] = "machine à café" },
},


["Lighting"] = {
  [1] = { ["object"] = "v_corp_cd_desklamp", ["price"] = 0, ["name"] = "Corps de Lampe de bureau" },
  [2] = { ["object"] = "v_res_desklamp", ["price"] = 0, ["name"] = "Lampe de bureau" },
  [3] = { ["object"] = "v_res_d_lampa", ["price"] = 0, ["name"] = "Lampe A" },
  [4] = { ["object"] = "v_res_fa_lamp1on", ["price"] = 0, ["name"] = "Lampe 1" },
  [5] = { ["object"] = "v_res_fh_floorlamp", ["price"] = 0, ["name"] = "Lampe d'intérieur" },
  [6] = { ["object"] = "v_res_fh_lampa_on", ["price"] = 0, ["name"] = "Lampe 2" },
  [7] = { ["object"] = "v_res_j_tablelamp1", ["price"] = 0, ["name"] = "Lampe de table" },
  [8] = { ["object"] = "v_res_j_tablelamp2", ["price"] = 0, ["name"] = "Lampe de table 2" },
  [9] = { ["object"] = "v_res_mdbedlamp", ["price"] = 0, ["name"] = "Lampe de lit" },
  [0] = { ["object"] = "v_res_mplanttongue", ["price"] = 0, ["name"] = "Lampe de plante" },
  [11] = { ["object"] = "v_res_mtblelampmod", ["price"] = 0, ["name"] = "Lampe de table 3" },
  [12] = { ["object"] = "v_res_m_lampstand", ["price"] = 0, ["name"] = "Lampe de support" },
  [13] = { ["object"] = "v_res_m_lampstand2", ["price"] = 0, ["name"] = "Lampe de support 2" },
  [14] = { ["object"] = "v_res_m_lamptbl", ["price"] = 0, ["name"] = "Lampe de table 4" },
  [15] = { ["object"] = "v_res_tre_lightfan", ["price"] = 0, ["name"] = "Lumière de ventilateur" },
  [16] = { ["object"] = "v_res_tre_talllamp", ["price"] = 0, ["name"] = "Lampe haute" },
  [17] = { ["object"] = "v_ret_fh_walllighton", ["price"] = 0, ["name"] = "Lumière de mur" },
  [18] = { ["object"] = "v_ret_gc_lamp", ["price"] = 0, ["name"] = "Lampe" },
  [19] = { ["object"] = "prop_dummy_light", ["price"] = 0, ["name"] = "Lumière vascillante" },
  [0] = { ["object"] = "prop_ld_cont_light_01", ["price"] = 0, ["name"] = "Lumière murale de coté" },
  [21] = { ["object"] = "V_44_D_emis", ["price"] = 0, ["name"] = "Lumière Test" },
},


["Tables"] = {
  [1] = { ["object"] = "v_res_d_coffeetable", ["price"] = 0, ["name"] = "Table à café 1" },
  [2] = { ["object"] = "v_res_d_roundtable", ["price"] = 0, ["name"] = "Table ronde" },
  [3] = { ["object"] = "v_res_d_smallsidetable", ["price"] = 0, ["name"] = "Petite Table" },
  [4] = { ["object"] = "v_res_fh_coftablea", ["price"] = 0, ["name"] = "Table A" },
  [5] = { ["object"] = "v_res_fh_coftableb", ["price"] = 0, ["name"] = "Table B" },
  [6] = { ["object"] = "v_res_fh_coftbldisp", ["price"] = 0, ["name"] = "Table C" },
  [7] = { ["object"] = "v_res_fh_diningtable", ["price"] = 0, ["name"] = "Table de diner" },
  [8] = { ["object"] = "v_res_j_coffeetable", ["price"] = 0, ["name"] = "Table à café 2" },
  [9] = { ["object"] = "v_res_j_lowtable", ["price"] = 0, ["name"] = "Table basse" },
  [0] = { ["object"] = "v_res_mdbedtable", ["price"] = 0, ["name"] = "Table-lit" },
  [11] = { ["object"] = "v_res_mddesk", ["price"] = 0, ["name"] = "Bureau" },
  [12] = { ["object"] = "v_res_msidetblemod", ["price"] = 0, ["name"] = "Table de coté" },
  [13] = { ["object"] = "v_res_m_console", ["price"] = 0, ["name"] = "Table de console" },
  [14] = { ["object"] = "v_res_m_dinetble_replace", ["price"] = 0, ["name"] = "Table à diner 2" },
  [15] = { ["object"] = "v_res_m_h_console", ["price"] = 0, ["name"] = "Table à console 2" },
  [16] = { ["object"] = "v_res_m_stool", ["price"] = 0, ["name"] = "Tabouret" },
  [17] = { ["object"] = "v_res_tre_sideboard", ["price"] = 0, ["name"] = "Table de coté 2" },
  [18] = { ["object"] = "v_res_tre_table2", ["price"] = 0, ["name"] = "Table 2" },
  [19] = { ["object"] = "v_res_tre_tvstand", ["price"] = 0, ["name"] = "Table de télévision" },
  [0] = { ["object"] = "v_res_tre_tvstand_tall", ["price"] = 0, ["name"] = "Grande Table de télévision" },
  [21] = { ["object"] = "v_med_p_coffeetable", ["price"] = 0, ["name"] = "Table moyenne à café" },
  [22] = { ["object"] = "v_med_p_desk", ["price"] = 0, ["name"] = "bureau moyen" },
  [23] = { ["object"] = "prop_yacht_table_01", ["price"] = 0, ["name"] = "Table de Yacht 1" },
  [24] = { ["object"] = "prop_yacht_table_02", ["price"] = 0, ["name"] = "Table de Yacht 2" },
  [25] = { ["object"] = "prop_yacht_table_03", ["price"] = 0, ["name"] = "Table de Yacht 3" },
  [26] = { ["object"] = "v_ret_csr_table", ["price"] = 0, ["name"] = "CSR Table" },
  [27] = { ["object"] = "hei_heist_din_table_06", ["price"] = 0, ["name"] = "Table et chaises de diner" },
},

["Plantes"] = {
  [1] = { ["object"] = "prop_fib_plant_01", ["price"] = 0, ["name"] = "Plante 1" },
  [2] = { ["object"] = "v_corp_bombplant", ["price"] = 0, ["name"] = "Plante 2" },    
  [3] = { ["object"] = "v_res_mflowers", ["price"] = 0, ["name"] = "Plante Fleurs" }, 
  [4] = { ["object"] = "v_res_mvasechinese", ["price"] = 0, ["name"] = "Plante Chinoise" }, 
  [5] = { ["object"] = "v_res_m_bananaplant", ["price"] = 0, ["name"] = "Plante Banane" }, 
  [6] = { ["object"] = "v_res_m_palmplant1", ["price"] = 0, ["name"] = "Plante Palmier" },  
  [7] = { ["object"] = "v_res_m_palmstairs", ["price"] = 0, ["name"] = "Plante Palmier 2" },  
  [8] = { ["object"] = "v_res_m_urn", ["price"] = 0, ["name"] = "Plante 3" },  
  [9] = { ["object"] = "v_res_rubberplant", ["price"] = 0, ["name"] = "Plante 4" }, 
  [0] = { ["object"] = "v_res_tre_plant", ["price"] = 0, ["name"] = "Plante 5" }, 
  [11] = { ["object"] = "v_res_tre_tree", ["price"] = 0, ["name"] = "Plante 6" }, 
  [12] = { ["object"] = "v_med_p_planter", ["price"] = 0, ["name"] = "Plante 7" }, 
  [13] = { ["object"] = "v_ret_flowers", ["price"] = 0, ["name"] = "Fleurs" },
  [14] = { ["object"] = "v_ret_j_flowerdisp", ["price"] = 0, ["name"] = "Fleurs 1" },
  [15] = { ["object"] = "v_ret_j_flowerdisp_white", ["price"] = 0, ["name"] = "Fleurs 2" },
  [16] = { ["object"] = "apa_mp_h_acc_vase_flowers_01", ["price"] = 0, ["name"] = "Fleurs 3" },
  [17] = { ["object"] = "apa_mp_h_acc_vase_flowers_02", ["price"] = 0, ["name"] = "Fleurs 4" },
  [18] = { ["object"] = "xm_prop_x17_xmas_tree_int", ["price"] = 0, ["name"] = "arbre de noël" },
},

["Kitchen"] = {
  [1] = { ["object"] = "prop_washer_01", ["price"] = 0, ["name"] = "Machine à laver 1" },
  [2] = { ["object"] = "prop_washer_02", ["price"] = 0, ["name"] = "Machine à laver 2" },
  [3] = { ["object"] = "prop_washer_03", ["price"] = 0, ["name"] = "Machine à laver 3" },
  [4] = { ["object"] = "prop_washing_basket_01", ["price"] = 0, ["name"] = "lave basquette" },
  [5] = { ["object"] = "v_res_fridgemoda", ["price"] = 0, ["name"] = "Frigo 1" },
  [6] = { ["object"] = "v_res_fridgemodsml", ["price"] = 0, ["name"] = "Frigo 2" },
  [7] = { ["object"] = "prop_fridge_01", ["price"] = 0, ["name"] = "Frigo 3" },
  [8] = { ["object"] = "prop_fridge_03", ["price"] = 0, ["name"] = "Frigo 4" },
  [9] = { ["object"] = "prop_cooker_03", ["price"] = 0, ["name"] = "cuisine" },
  [0] = { ["object"] = "prop_micro_01", ["price"] = 0, ["name"] = "Microvague 1" },
  [11] = { ["object"] = "prop_micro_02", ["price"] = 0, ["name"] = "Microvague 2" },
  [12] = { ["object"] = "prop_wok", ["price"] = 0, ["name"] = "Wok" },
  [13] = { ["object"] = "v_res_cakedome", ["price"] = 0, ["name"] = "Plat à cakes" },
  [14] = { ["object"] = "v_res_fa_chopbrd", ["price"] = 0, ["name"] = "planche à découper" },
  [15] = { ["object"] = "v_res_mutensils", ["price"] = 0, ["name"] = "Ustensils" },
  [16] = { ["object"] = "v_res_pestle", ["price"] = 0, ["name"] = "Pilon" },
  [17] = { ["object"] = "v_ret_ta_paproll", ["price"] = 0, ["name"] = "rouleau de papier 1" },
  [18] = { ["object"] = "v_ret_ta_paproll2", ["price"] = 0, ["name"] = "rouleau de papier 2" },
  [19] = { ["object"] = "v_ret_fh_pot01", ["price"] = 0, ["name"] = "Bol 1" },
  [0] = { ["object"] = "v_ret_fh_pot02", ["price"] = 0, ["name"] = "Bol 2" },
  [21] = { ["object"] = "v_ret_fh_pot05", ["price"] = 0, ["name"] = "Bol 3" },
  [22] = { ["object"] = "prop_pot_03", ["price"] = 0, ["name"] = "Bol 4" },
  [23] = { ["object"] = "prop_pot_04", ["price"] = 0, ["name"] = "Bol 5" },
  [24] = { ["object"] = "prop_pot_05", ["price"] = 0, ["name"] = "Bol 6" },
  [25] = { ["object"] = "prop_pot_06", ["price"] = 0, ["name"] = "Bol 7" },
  [26] = { ["object"] = "prop_pot_rack", ["price"] = 0, ["name"] = "Bol rangement" },
  [27] = { ["object"] = "prop_kitch_juicer", ["price"] = 0, ["name"] = "Pressoir à jus" },
},


["Bathroom"] = {
  [1] = { ["object"] = "prop_ld_toilet_01", ["price"] = 0, ["name"] = "Toilette 1" },
  [2] = { ["object"] = "prop_toilet_01", ["price"] = 0, ["name"] = "Toilette 2" },
  [3] = { ["object"] = "prop_toilet_02", ["price"] = 0, ["name"] = "Toilette 3" },
  [4] = { ["object"] = "prop_sink_02", ["price"] = 0, ["name"] = "Evier 1" },
  [5] = { ["object"] = "prop_sink_04", ["price"] = 0, ["name"] = "Evier 2" },
  [6] = { ["object"] = "prop_sink_05", ["price"] = 0, ["name"] = "Evier 3" },
  [7] = { ["object"] = "prop_sink_06", ["price"] = 0, ["name"] = "Evier 4" },
  [8] = { ["object"] = "prop_soap_disp_01", ["price"] = 0, ["name"] = "Dispensaire à savon" },
  [9] = { ["object"] = "prop_shower_rack_01", ["price"] = 0, ["name"] = "rangement de douche" },
  [0] = { ["object"] = "prop_handdry_01", ["price"] = 0, ["name"] = "sèche mains 1" },
  [11] = { ["object"] = "prop_handdry_02", ["price"] = 0, ["name"] = "sèche mains 2" },
  [12] = { ["object"] = "prop_towel_rail_01", ["price"] = 0, ["name"] = "Rail de Serviette 1" },
  [13] = { ["object"] = "prop_towel_rail_02", ["price"] = 0, ["name"] = "Rail de Serviette 2" },
  [14] = { ["object"] = "prop_towel_01", ["price"] = 0, ["name"] = "Serviette 1" },
  [15] = { ["object"] = "v_res_mbtowel", ["price"] = 0, ["name"] = "Serviette 2" },
  [16] = { ["object"] = "v_res_mbtowelfld", ["price"] = 0, ["name"] = "Serviette 3" },
  [17] = { ["object"] = "v_res_mbath", ["price"] = 0, ["name"] = "baignoire" },
  [18] = { ["object"] = "v_res_mbsink", ["price"] = 0, ["name"] = "Evier" },
},

["Medical"] = {
  [1] = { ["object"] = "v_med_barrel", ["price"] = 0, ["name"] = "Barril" },
  [2] = { ["object"] = "v_med_apecrate", ["price"] = 0, ["name"] = "caisse" },
  [3] = { ["object"] = "v_med_apecratelrg", ["price"] = 0, ["name"] = "Large caisse" },
  [4] = { ["object"] = "v_med_bed1", ["price"] = 0, ["name"] = "Lit 1" },
  [5] = { ["object"] = "v_med_bed2", ["price"] = 0, ["name"] = "Lit 2" },
  [6] = { ["object"] = "v_med_bedtable", ["price"] = 0, ["name"] = "Lit Table" },
  [7] = { ["object"] = "v_med_bench1", ["price"] = 0, ["name"] = "Banc 1" },
  [8] = { ["object"] = "v_med_bench2", ["price"] = 0, ["name"] = "Banc 2" },
  [9] = { ["object"] = "v_med_benchcentr", ["price"] = 0, ["name"] = "Banc Center" },
  [0] = { ["object"] = "v_med_benchset1", ["price"] = 0, ["name"] = "Banc Set" },
  [11] = { ["object"] = "v_med_bigtable", ["price"] = 0, ["name"] = "Table" },
  [12] = { ["object"] = "v_med_bin", ["price"] = 0, ["name"] = "Poubelle 1" },
  [13] = { ["object"] = "v_med_centrifuge1", ["price"] = 0, ["name"] = "Centrifuge" },
  [14] = { ["object"] = "v_med_cooler", ["price"] = 0, ["name"] = "CGlacière" },
  [15] = { ["object"] = "v_med_cor_ceilingmonitor", ["price"] = 0, ["name"] = "écran" },
  [16] = { ["object"] = "v_med_cor_autopsytbl", ["price"] = 0, ["name"] = "Table d'autopsie" },
  [17] = { ["object"] = "v_med_cor_cembin", ["price"] = 0, ["name"] = "Poubelle 2" },
  [18] = { ["object"] = "v_med_cor_cemtrolly2", ["price"] = 0, ["name"] = "Chariot" },
  [19] = { ["object"] = "v_med_cor_chemical", ["price"] = 0, ["name"] = "Chem" },
  [0] = { ["object"] = "v_med_cor_emblmtable", ["price"] = 0, ["name"] = "BLM Table" },
  [21] = { ["object"] = "v_med_cor_fileboxa", ["price"] = 0, ["name"] = "boite a dossiers" },
  [22] = { ["object"] = "v_med_cor_filingcab", ["price"] = 0, ["name"] = "dossiers" },
  [23] = { ["object"] = "v_med_cor_hose", ["price"] = 0, ["name"] = "tuyau" },
  [24] = { ["object"] = "v_med_cor_largecupboard", ["price"] = 0, ["name"] = "Large coupe" },
  [25] = { ["object"] = "v_med_cor_lightbox", ["price"] = 0, ["name"] = "Boite à lumière" },
  [26] = { ["object"] = "v_med_cor_medstool", ["price"] = 0, ["name"] = "Medstool" },
  [27] = { ["object"] = "v_med_cor_minifridge", ["price"] = 0, ["name"] = "Mini frigo" },
  [28] = { ["object"] = "v_med_cor_papertowels", ["price"] = 0, ["name"] = "Serviette en papier" },
  [29] = { ["object"] = "v_med_cor_photocopy", ["price"] = 0, ["name"] = "Photocopie" },
  [0] = { ["object"] = "v_med_cor_tvstand", ["price"] = 0, ["name"] = "meuble de télévision" },
  [31] = { ["object"] = "v_med_cor_wallunita", ["price"] = 0, ["name"] = "Mur" },
  [32] = { ["object"] = "v_med_examlight", ["price"] = 0, ["name"] = "lumière d'examen" },
  [33] = { ["object"] = "v_med_gastank", ["price"] = 0, ["name"] = "Réservoir d'essence" },
  [34] = { ["object"] = "v_med_hazmatscan", ["price"] = 0, ["name"] = "Scan Hazmat" },
  [35] = { ["object"] = "v_med_hospheadwall1", ["price"] = 0, ["name"] = "Mur de tête" },
  [36] = { ["object"] = "v_med_hospseating1", ["price"] = 0, ["name"] = "Sièges" },
  [37] = { ["object"] = "v_med_hosptable", ["price"] = 0, ["name"] = "Table d'Hospital" },
  [38] = { ["object"] = "v_med_latexgloveboxblue", ["price"] = 0, ["name"] = "Boites à gants" },
  [39] = { ["object"] = "v_med_medwastebin", ["price"] = 0, ["name"] = "Corbeille" },
  [40] = { ["object"] = "v_med_oscillator3", ["price"] = 0, ["name"] = "Oscillateur" },
  [41] = { ["object"] = "prop_ld_health_pack", ["price"] = 0, ["name"] = "Pack de soins" },
}
}

lookuptable = {}
dropdowntable = {}
hashtable = {}

for category,v in pairs(furni.objects) do 
dropdowntable[category] = {}

for o,k in pairs(v) do

  local hash = GetHashKey(k.object)
  hashtable[hash] = k

  local id = k.object or "none"
  local name = k.name or "none"
  local price = k.price or 9999

  lookuptable[id] = k

  table.insert(dropdowntable[category],{id = id,name = name,price = price})
end 
end 

for k,v in pairs(furni.objects) do
for k,v in pairs(v) do
  v.id = v.object
end
end

if not Config.UsingNativeHousing then
TriggerEvent('esx:getSharedObject', function(obj) ESX = obj; end)
Citizen.CreateThread(function(...) while not ESX do TriggerEvent('esx:getSharedObject',function(obj) ESX = obj; end); Citizen.Wait(0); end; end)
end

mLibs = exports["meta_libs"]