Lang = {
  ['dispatch_name']         	= 'Dispatch: ',
  ['police_notify']         	= 'Ongoing BANK ROBBERY in ^1%s^0 at ^3%s^0',
  ['silent_alarm']         	  = 'Une alarme silencieuse à était declancher à ^3%s',
  -- Drilling Draw Texts:
  ['safe_not_drilled']        = '~r~[E]~s~ | Percer',
  ['safe_drilled']            = 'Casier ~g~[percer]~s~',
  ['safe_destroyed']          = 'Casier ~r~[detruit]~s~',
  ['safe_reward_txt']         = 'Vous avez trouver ~y~%sx~s~ %s',
  -- Drilling Texts:
  ['safe_destroyed_noti']     = 'Casier ~r~detruit',
  ['safe_arealdy_robbed']     = 'Casier déjà ~g~volée~s~!',
  ['you_destroyed_safe']      = 'Vous avez ~r~detruit~s~ la serrure!',
  ['drilling_paused']         = 'Vous avez ~y~arreter~s~ de percer',
  ['safe_drilled_by_ply']     = 'Casier déjà percer',
  ['drill_item_usable']       = 'Vous avez finis de percer',
  ['drill_item_not_usable']   = 'Vous avez cassée la Perceuse',
  -- Bank Draw Texts:
  ['hack_keypad_1']           = '~r~[E]~s~ | Hack Keypad',
  ['open_keypad_1']           = '~y~[G]~s~ | Utiliser La Carte d\'Acces',
  ['hack_keypad_2']           = '~r~[K]~s~ | Hack Keypad',
  ['open_keypad_2']           = '~y~[G]~s~ | Utiliser La Carte d\'Acces',
  ['lockpick_desk_door']      = '~r~[E]~s~ | Lockpick La Porte',
  ['open_desk_door']          = '~r~[E]~s~ | Ouvrir La Porte',
  ['open_desk_door_pol']      = '~r~[E]~s~ | Ouvrir la porte | ~r~[G]~s~ Securiser la Bank',
  ['close_desk_door']         = '~r~[E]~s~ | Fermer La Porte',
  ['close_desk_door_pol']     = '~r~[E]~s~ | Close Door | ~r~[G]~s~ Securiser la Bank',
  ['desk_cash_not_robbed']    = '~r~[E]~s~ | Rob Petty Cash',
  ['desk_cash_robbed']        = 'Cash ~g~[volée]~s~',
  ['power_box_not_disabled']  = '~r~[E]~s~ | Desactiver Electriciter',
  ['power_box_disabled']      = 'Electriciter ~r~[desactiver]~s~',
  ['open_pacific_safe']       = '~r~[E]~s~ | Ouvrir casier',
  ['pacific_safe_cracked']    = 'Casier ~g~[cracked]~s~',
  ['close_vault_dr']          = '~g~[E]~s~ | Fermer le coffre',
  ['open_vault_dr']           = '~g~[E]~s~ | Ouvrir le coffre',
  ['open_vault_dr_pol']       = '~g~[E]~s~ Ouvrir le coffre | ~r~[G]~s~ Fermer le coffre',
  -- Bank Text:
  ['bank_in_lockdown']        = 'BANK IN LOCKDOWN',
  ['no_drill']                = 'Vous avez besoin d\'une perceuse',
  ['no_hacking_dev']          = 'Vous avez besoin d\'un Outil de Hack',
  ['no_access_card']          = 'Vous avez besoin d\'une carte d\'acces',
  ['no_lockpick']             = 'Vous avez besoin d\'un Lockpick',
  ['no_hammerwirecutter']     = 'Vous avez besoin d\'un Marteau et d\'un Wire Cutter',
  ['get_closer_to_door']      = 'Move closer to the door to interact.',
  ['vault_dr_must_close']     = 'You need to close the vault door first!',
  ['found_access_card']       = 'Vous avez trouver une carte d\'acces',
  ['hacker_dev_corrupted']    = 'Hacker Device got corrupted, no longer usable.',
  ['you_secured_bank']        = 'You secured the bank. All banks will be unlocked!',
  ['no_access_to_cam']        = 'Vous n\'avez pas acces au camera!',
  ['notify_free_time']        = 'Electriciter couper. Vous avez ~b~%s secondes~s~ avant que l\'alarme soit declancher!',
  ['extra_free_time_added']   = 'Vous avez gagnée du temps. Vous avez: ~b~%s secondes~s~ avant que l\'alarme soit declancher!',
  -- Camera:
  ['camera_not_exist']        = 'Entered camera ID does not exist.',

}
